"""Sync models with schema

Revision ID: 4c6495ff9478
Revises: 1e19d826e10f
Create Date: 2026-01-24 13:41:46.109893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6495ff9478'
down_revision: Union[str, None] = '1e19d826e10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_embeddings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('event_embeddings', sa.Column('model_name', sa.Text(), nullable=True))
    op.add_column('event_embeddings', sa.Column('embedding_version', sa.Text(), nullable=True))
    op.add_column('event_embeddings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('event_embeddings_embedding_idx'), table_name='event_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('expert_embeddings', sa.Column('model_name', sa.Text(), nullable=True))
    op.add_column('expert_embeddings', sa.Column('embedding_version', sa.Text(), nullable=True))
    op.add_column('expert_embeddings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('expert_embeddings_embedding_idx'), table_name='expert_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('expert_embeddings_embedding_idx'), 'expert_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('expert_embeddings', 'created_at')
    op.drop_column('expert_embeddings', 'embedding_version')
    op.drop_column('expert_embeddings', 'model_name')
    op.create_index(op.f('event_embeddings_embedding_idx'), 'event_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('event_embeddings', 'created_at')
    op.drop_column('event_embeddings', 'embedding_version')
    op.drop_column('event_embeddings', 'model_name')
    op.drop_column('event_embeddings', 'summary')
    # ### end Alembic commands ###
