"""Add chat channels and attachments

Revision ID: fb8a5326981a
Revises: 4c6495ff9478
Create Date: 2026-02-26 14:47:41.331687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fb8a5326981a'
down_revision: Union[str, None] = '4c6495ff9478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Create the ENUM type first
    channel_type = postgresql.ENUM('DIRECT', 'GROUP', 'EVENT_ROOM', name='channeltype')
    channel_type.create(op.get_bind())
    
    op.add_column('conversations', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('type', sa.Enum('DIRECT', 'GROUP', 'EVENT_ROOM', name='channeltype'), nullable=False))
    op.add_column('event_embeddings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('event_embeddings', sa.Column('model_name', sa.Text(), nullable=True))
    op.add_column('event_embeddings', sa.Column('embedding_version', sa.Text(), nullable=True))
    op.add_column('event_embeddings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('expert_embeddings', sa.Column('model_name', sa.Text(), nullable=True))
    op.add_column('expert_embeddings', sa.Column('embedding_version', sa.Text(), nullable=True))
    op.add_column('expert_embeddings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert_embeddings', 'created_at')
    op.drop_column('expert_embeddings', 'embedding_version')
    op.drop_column('expert_embeddings', 'model_name')
    op.drop_column('event_embeddings', 'created_at')
    op.drop_column('event_embeddings', 'embedding_version')
    op.drop_column('event_embeddings', 'model_name')
    op.drop_column('event_embeddings', 'summary')
    op.drop_column('conversations', 'type')
    op.drop_column('conversations', 'name')
    
    # Drop the ENUM type
    channel_type = postgresql.ENUM('DIRECT', 'GROUP', 'EVENT_ROOM', name='channeltype')
    channel_type.drop(op.get_bind())
    op.drop_table('attachments')
    # ### end Alembic commands ###
