export const APU_DEGREES = [
    "Software Engineering",
    "Computer Science",
    "CS (AI)",
    "CS (Data Analytics)",
    "CS (Cyber Security)",
    "CS (Digital Forensics)",
    "Information Technology",
    "IT (FinTech)",
    "IT (Business Information Systems)",
    "IT (Sustainable Computing)",
    "IT (Information System Security)",
    "IT (Cloud Engineering)",
    "IT (IoT)",
    "IT (Digital Transformation)",
    "Computer Games Development",
    "Financial Technology (FinTech)",
    "Interactive Media (VR/AR)",
    "Banking and Finance (Investment Analytics)",
    "Banking and Finance (FinTech)",
    "Banking and Finance",
    "Actuarial Studies",
    "Actuarial Studies (Data Analytics)",
    "Actuarial Studies (FinTech)",
    "Accounting and Finance",
    "Accounting and Finance (Forensic Accounting)",
    "Accounting and Finance (Forex and Investments)",
    "Accounting and Finance (Accounting Technology)",
];

export const COUNTRIES = [
    "Malaysia",
    "Singapore",
    "Indonesia",
    "Thailand",
    "Vietnam",
    "Philippines",
    "China",
    "India",
    "Japan",
    "South Korea",
    "Taiwan",
    "Hong Kong",
    "Australia",
    "New Zealand",
    "United Kingdom",
    "United States",
    "Canada",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Switzerland",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Russia",
    "Ukraine",
    "Poland",
    "Brazil",
    "Argentina",
    "Mexico",
    "South Africa",
    "Egypt",
    "United Arab Emirates",
    "Saudi Arabia",
    "Qatar",
    "Turkey",
    "Iran",
    "Pakistan",
    "Bangladesh",
    "Sri Lanka",
    "Nepal",
    "Myanmar",
    "Cambodia",
    "Laos",
    "Brunei",
    "Other"
].sort();
